version: '3.8'

services:
  backend:
    # image: marou974/m0b5-back:${BACK_VERSION}   # to test remote images
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment:
      - APP_ENV=${APP_ENV:-local}
    volumes:
      - ./backend:/app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    # image: marou974/m0b5-front:${FRONT_VERSION}   # to test remote images
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env 
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL:-http://backend:8000}
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
