name: Python application CI/CD
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade 
          cd ./backend
          pip install -r requirements.txt

      # tests
      - name: Run unit tests
        run: |
          pytest
